version: '3'

services:
  ML-tuner:
    image: gaussianprocessregressortool
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=mysql://root:password@db/axdb
      - N_TRIALS=5
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=axdb